const express=require('express')
const route=express.Router()
const adminController =require ("../controller/adminController")
const sessioncontroller=require("../controller/sessioncontroller")
const  semesterController=require("../controller/semesterController")
const departmentController=require("../controller/departmentController")
const coursesController=require("../controller/coursesController")
const registrationController=require("../controller/registrationController")
route.post("/createAdmin",adminController.createAdmin)
route.post("/loginAdmin",adminController.loginAdmin)

route.post("/createSession",sessioncontroller.createSession)
route.get("/getsession",sessioncontroller.getsession)
route.post("/createsemester",semesterController.createSemester)
route.get("/getsemester",semesterController.getsemester)
route.post("/createdepartment",departmentController.createdepartment)
route.get("/getdepartment",departmentController.getdepartment)
route.get("/getdepartmentId/:id",departmentController.getdepartmentId)
route.patch("/updatedepartment/:id",departmentController.updatedepartment)
route.delete("/deletedepartment/:id",departmentController.deletedepartment)
route.post("/createcourses",coursesController.createcourses)
route.get("/courseget",coursesController.courseget)
route.get("/getcoursesId/:id",coursesController.getcoursesId)
route.patch("/updatecourses/:id",coursesController.updatecourses)
route.delete("/deletecourses/:id",coursesController.deletecourses)
route.post("/createreg",registrationController.createreg)
route.get("/getReg",registrationController.getReg)
route.get("/getregId/:id",registrationController.getregId)
route.patch("/updateData/:id",registrationController.updateData)
route.delete("/deleteregistration/:id",registrationController.deleteregistration)


module.exports=route