const express =require('express')
const app=express()
const router=require('./router/route')
require("dotenv").config()
const port=process.env.port
require('./dbcon/cn')
const cors=require('cors')
app.use(express.json())
app.use(cors())
app.use(router)
app.listen(port,()=>console.log(`server is running on port:${port}`))